version: "3.7"
services:
  jenkins:
    build:
      context: .
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    restart: always
    networks:
      - proyectos-app

volumes:
  jenkins_home:

networks:
  proyectos-app:
